name: Build CS3

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up JDK 11
      uses: actions/setup-java@v2
      with:
        java-version: '11'
        distribution: 'adopt'  # Add this line

    - name: Grant execute permission for gradlew
      run: chmod +x gradlew

    - name: Build with Gradle
      run: ./gradlew buildCs3

    - name: Upload CS3 file
      uses: actions/upload-artifact@v3
      with:
        name: MyWordPressProvider
        path: build/libs/MyWordPressProvider.cs3